import turtle

def shiot():
	turtle.pendown()
	turtle.setheading(-135)
	turtle.forward(250)
	turtle.penup()
	turtle.back(150)
	turtle.pendown()
	turtle.setheading(-45)
	turtle.forward(150)
	turtle.penup()
def u():
	turtle.pendown()
	turtle.forward(300)
	turtle.penup()
	turtle.back(150)
	turtle.pendown()
	turtle.right(90)
	turtle.forward(150)
	turtle.penup()
def ieung():
	turtle.pendown()
	turtle.setheading(180)
	turtle.circle(100)
	turtle.penup()
	
turtle.penup()	
turtle.goto(-550,250)
turtle.pendown()
turtle.forward(200)
shiot()
turtle.setheading(-90)
turtle.forward(50)
turtle.setheading(180)
turtle.forward(250)
turtle.setheading(0)
u()
turtle.home()
turtle.goto(-70,250)
shiot()
turtle.setheading(0)
turtle.forward(50)
turtle.setheading(90)
turtle.back(50)
u()
turtle.home()
turtle.back(50)
ieung()
turtle.home()
turtle.forward(450)
turtle.setheading(90)
turtle.forward(200)
turtle.setheading(180)
u()
turtle.back(200)
ieung()
turtle.back(150)
turtle.setheading(-90)
turtle.forward(350)
turtle.setheading(180)
u()
turtle.hideturtle()

turtle.exitonclick()
